clear;
arr_res = table2array(readtable('out_array.csv'));
arr_armot_res = table2array(readtable('out_array_amortised.csv'));
arr_static_res = table2array(readtable('out_array_static.csv'));
list_res = table2array(readtable('out_list.csv'));
%ARRAY
x_array = arr_res(:,1);
y_array = arr_res(:,2);
error_array = arr_res(:,3);
x1_array = arr_res(:, 4);
y1_array = arr_res(:, 5);
error1_array = arr_res(:, 6);
k_array = arr_res(1, 7);
%ARRAY AMORTISED
x_arr_am = arr_armot_res(:,1);
y_arr_am = arr_armot_res(:,2);
error_arr_am = arr_armot_res(:,3);
x1_arr_am = arr_armot_res(:,4);
y1_arr_am = arr_armot_res(:, 5);
error1_arr_am = arr_armot_res(:,6);
k_arr_am = arr_armot_res(1, 7);
b_arr_am = arr_armot_res(3, 7);
%ARRAY STATIC
x_arr_st = arr_static_res(:,1);
y_arr_st = arr_static_res(:,2);
error_arr_st = arr_static_res(:,3);
x1_arr_st = arr_static_res(:,4);
y1_arr_st = arr_static_res(:, 5);
error1_arr_st = arr_static_res(:,6);
k_arr_st = arr_static_res(1, 7);
b_arr_st = arr_static_res(3, 7);
%LIST
x_list = list_res(:,1);
y_list = list_res(:,2);
error_list = list_res(:,3);
x1_list = list_res(:,4);
y1_list = list_res(:, 5);
error1_list = list_res(:,6);
k_list = list_res(1, 7);
b_list = list_res(3, 7);
hold on;
xlabel('N');
ylabel('t');
errorbar(x_array, y_array, error_array, '.');
x = 1:100:35000;
y = k_array*(x + x.^2);
plot(x, y);
hold off;
figure;
hold on;
xlabel('N');
ylabel('t');
x = 1:1:200;
y = k_array*(x + x.^2);
plot(x, y);
y = 2^b_arr_am * x.^k_arr_am;
plot(x, y);
y = 2^b_list*x.^k_list;
plot(x, y);
hold off;
figure;
hold on;
xlabel('N');
ylabel('t');
errorbar(x_arr_am, y_arr_am, error_arr_am, '.');
errorbar(x_list, y_list, error_list, '.');
x = 0:1000:70000000;
y = 2^b_arr_am * x.^k_arr_am;
plot(x, y);
y = 2^b_list*x.^k_list;
plot(x, y);
hold off;
figure;
hold on;
ylabel('t');
xlabel('N^2 + N');
errorbar(x1_array, y1_array, error1_array, '.');
x = 0:10000:1200000000;
y = k_array*x;
plot(x, y);
hold off;
figure;
hold on;
xlabel('log_2(N)');
ylabel('log_2(t)');
errorbar(x1_arr_am, y1_arr_am, error1_arr_am, '.');
x = 12:1:26;
y = b_arr_am + x*k_arr_am;
plot(x, y);
hold off;
figure; 
hold on;
xlabel('log_2(N)');
ylabel('log_2(t)');
y = b_list + k_list*x;
plot(x, y);
errorbar(x1_list, y1_list, error1_list, '.');
hold off;
figure;
hold on;
xlabel('N');
ylabel('t');
x = 1:10000:70000000;
y = 2^(b_arr_am)*x.^k_arr_am;
plot(x, y);
y = 2^(b_arr_st)*x.^k_arr_st;
plot(x, y);
errorbar(x_arr_am, y_arr_am, error_arr_am, '.');
errorbar(x_arr_st, y_arr_st, error_arr_st, '.');
